# Generated by Django 2.1.5 on 2019-04-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190221_0705'),
        ('event', '0003_auto_20190407_1337'),
    ]

    operations = [
    ]
