# Generated by Django 2.1.5 on 2019-03-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190221_0705'),
        ('event', '0002_auto_20190318_1243'),
    ]

    operations = [
    ]
