# Generated by Django 2.1.5 on 2019-04-07 13:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190407_1337'),
        ('users', '0003_merge_20190407_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^[0-9]{16}$')])),
                ('security_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[0-9]{3}$')])),
                ('expiration_month', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{2}$')])),
                ('expiration_year', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[0-9]{2}$')])),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='profile', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(related_name='notifications', to='users.Notification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_contact',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_event_host',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_event_invite',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='on_event_update_delete',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='credit_card',
            field=models.ManyToManyField(related_name='credit_card', to='users.Credit'),
        ),
    ]
