# Generated by Django 2.1.5 on 2019-04-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190407_1418'),
        ('users', '0003_merge_20190406_1422'),
    ]

    operations = [
    ]
